LOCAL_FILE_PATH_BUILDER = "/application/assets"
WORLD_MAPS_FILE_PATH = f"{LOCAL_FILE_PATH_BUILDER}/world_maps"

REGION = "GMS"
VERSION = "247"

BASE_URL_ENDPOINT_BUILDER = f"https://maplestory.io/api/{REGION}/{VERSION}"
BASE_URL_ENDPOINT_STORE_BUILDER = f"https://store.maplestory.io/api/json/{REGION}/{VERSION}"

ALL_WORLDMAP_ENDPOINT = f"{BASE_URL_ENDPOINT_BUILDER}/map/worldmap"
ALL_WZ_IMAGE_ASSETS_ENDPOINT = f"{BASE_URL_ENDPOINT_STORE_BUILDER}/images.json"